easy_admin:
  site_name: 'LV Social Wall'
  design:
    brand_color: '#03A9F4'
    assets:
      css:
        - 'css/easy_admin.css'
      js:
        - 'js/easy_admin.js'
  list:
    collapse_actions: true
    batch_actions: ['delete']
    actions:
      - { name: 'edit', icon: 'pencil' }
      - { name: 'delete', icon: 'trash' }
  entities:
    Event:
      class: App\Entity\Event
      image_base_path: 'http://127.0.0.1:8000/uploads/events'
      form:
        fields:
          - { property: 'name' }
          - { property: 'startDate' }
          - { property: 'endDate', type_options: { required: false } }
          - { property: 'location' }
          - { property: 'hashtags'}
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'callToAction' }
          - { property: 'directMessageData', label: 'DM Twitter' }
          - { property: 'goodies' }
          - { property: 'bigPrize'}
      list:
        actions:
          - { name: 'play_event', type: 'route', icon: 'gamepad' }
          - { name: 'moderate', icon: 'comments'}
          - { name: 'edit', icon: 'pencil' }
          - { name: 'delete', icon: 'trash' }
        fields:
          - { property: 'image', type: 'image' }
          - { property: 'name' }
          - { property: 'startDate' }
          - { property: 'endDate' }
          - { property: 'location' }
      show:
        fields:
          - { property: 'image', type: 'image' }
          - { property: 'name' }
          - { property: 'startDate' }
          - { property: 'endDate' }
          - { property: 'location' }
    Goody:
      class: App\Entity\Goody
      image_base_path: 'http://127.0.0.1:8000/uploads/events'
      list:
        fields:
          - { property: 'image', type: 'image' }
          - { property: 'name' }
          - { property: 'quantity' }
      form:
        fields:
          - { property: 'name' }
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'quantity' }
      show:
        fields:
          - { property: 'image', type: 'image' }
          - { property: 'name' }
          - { property: 'quantity' }
    BigPrize:
      class: App\Entity\BigPrize
      image_base_path: 'http://127.0.0.1:8000/uploads/events'
      list:
        fields:
          - { property: 'image', type: 'image' }
          - { property: 'name' }
      form:
        fields:
          - { property: 'name' }
          - { property: 'imageFile', type: 'vich_image' }
    Tweet:
      class: App\Entity\Twitter\Tweet