security:
    providers:
        linkvalue_provider:
            id: Olivmai\LinkvalueOAuth2Bundle\Security\User\LinkvalueUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous:
            guard:
                authenticators:
                    - Olivmai\LinkvalueOAuth2Bundle\Security\Authenticator\LinkvalueAuthenticator
            provider: linkvalue_provider
            logout:
                path: app_logout
                target: login
